
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 08 09:40:45 PST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 6;
  public static final int AC = 12;
  public static final int POR = 4;
  public static final int ENTERO = 41;
  public static final int INT = 38;
  public static final int FOR = 44;
  public static final int CP = 11;
  public static final int NOT = 29;
  public static final int MENORIGUAL = 26;
  public static final int AND = 30;
  public static final int RANGE = 40;
  public static final int IGUAL = 22;
  public static final int CL = 15;
  public static final int IN = 43;
  public static final int OR = 31;
  public static final int DIV = 5;
  public static final int CC = 13;
  public static final int IF = 19;
  public static final int EXP = 7;
  public static final int CASTINGFLOATAENTERO = 35;
  public static final int MAYORIGUAL = 25;
  public static final int EOF = 0;
  public static final int ASIG = 28;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int DIF = 27;
  public static final int MENOS = 3;
  public static final int MENOR = 24;
  public static final int MOD = 8;
  public static final int IDENT = 37;
  public static final int DIVINT = 9;
  public static final int REAL = 42;
  public static final int MAYOR = 23;
  public static final int ELSE = 20;
  public static final int WHILE = 16;
  public static final int FLOAT = 39;
  public static final int CASTINGFLOATAEXPRESION = 36;
  public static final int AP = 10;
  public static final int ELIF = 21;
  public static final int DP = 34;
  public static final int PRINT = 18;
  public static final int DO = 17;
  public static final int AL = 14;
  public static final int PYC = 32;
  public static final int MAS = 2;
}

