
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int MENOS = 3;
  public static final int LOW = 15;
  public static final int IDENT = 29;
  public static final int ELSE = 22;
  public static final int CP = 8;
  public static final int PYC = 12;
  public static final int OR = 21;
  public static final int WHILE = 25;
  public static final int ALL = 9;
  public static final int NOT = 19;
  public static final int CLL = 10;
  public static final int IF = 24;
  public static final int POR = 4;
  public static final int AP = 7;
  public static final int DO = 26;
  public static final int LOE = 16;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int GOE = 18;
  public static final int PRINT = 23;
  public static final int GRE = 17;
  public static final int error = 1;
  public static final int EQ = 13;
  public static final int ENTERO = 28;
  public static final int FOR = 27;
  public static final int NEQ = 14;
  public static final int ASIG = 11;
  public static final int MAS = 2;
  public static final int UMINUS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "UMINUS",
  "AP",
  "CP",
  "ALL",
  "CLL",
  "ASIG",
  "PYC",
  "EQ",
  "NEQ",
  "LOW",
  "LOE",
  "GRE",
  "GOE",
  "NOT",
  "AND",
  "OR",
  "ELSE",
  "PRINT",
  "IF",
  "WHILE",
  "DO",
  "FOR",
  "ENTERO",
  "IDENT"
  };
}

