
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 26;
  public static final int MENOS = 3;
  public static final int ELSE = 19;
  public static final int CP = 10;
  public static final int IDENT = 14;
  public static final int PYC = 13;
  public static final int OR = 27;
  public static final int WHILE = 29;
  public static final int CK = 12;
  public static final int NOT = 8;
  public static final int MENIG = 22;
  public static final int IG = 24;
  public static final int IF = 18;
  public static final int POR = 4;
  public static final int MEN = 20;
  public static final int AP = 9;
  public static final int DO = 28;
  public static final int NIG = 25;
  public static final int AK = 11;
  public static final int MENOSUNARIO = 7;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int NUMERO = 15;
  public static final int MAYIG = 23;
  public static final int MAY = 21;
  public static final int NUMEROF = 16;
  public static final int FOR = 30;
  public static final int ASIG = 6;
  public static final int MAS = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "ASIG",
  "MENOSUNARIO",
  "NOT",
  "AP",
  "CP",
  "AK",
  "CK",
  "PYC",
  "IDENT",
  "NUMERO",
  "NUMEROF",
  "PRINT",
  "IF",
  "ELSE",
  "MEN",
  "MAY",
  "MENIG",
  "MAYIG",
  "IG",
  "NIG",
  "AND",
  "OR",
  "DO",
  "WHILE",
  "FOR"
  };
}

