
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Feb 06 19:20:02 PST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 36;
  public static final int POR = 4;
  public static final int NOTEQUAL = 17;
  public static final int FOR = 24;
  public static final int CP = 9;
  public static final int AND = 20;
  public static final int IGUALQUE = 13;
  public static final int MAYORQUE = 15;
  public static final int IGUAL = 7;
  public static final int OR = 21;
  public static final int TAB = 27;
  public static final int DIV = 5;
  public static final int IF = 18;
  public static final int EOF = 0;
  public static final int MAYOROIGUAL = 16;
  public static final int error = 1;
  public static final int COMA = 33;
  public static final int MENOS = 3;
  public static final int MENOSUNARIO = 6;
  public static final int CLL = 11;
  public static final int COM = 28;
  public static final int MENOROIGUAL = 12;
  public static final int EN = 34;
  public static final int MENORQUE = 14;
  public static final int POTENCIA = 29;
  public static final int ELSE = 19;
  public static final int FINAL = 31;
  public static final int WHILE = 25;
  public static final int VAR_NAME = 37;
  public static final int COCINA = 32;
  public static final int CORCHETE = 26;
  public static final int ALL = 10;
  public static final int AP = 8;
  public static final int ELIF = 35;
  public static final int DP = 30;
  public static final int PRINT = 23;
  public static final int PYC = 22;
  public static final int MAS = 2;
}

